owner: harsh778 
repo: harshsinghal.me-status 

sites:
  - name: Harsh Vardhan Singhal
    url: https://harshsinghal.me

status-website:

  baseUrl: /harshsinghal.me-status
  logoUrl: https://harshsinghal.me/Images/Favicons/android-chrome-192x192.png
  favicon: https://harshsinghal.me/Images/Favicons/favicon-32x32.png
  name: Status Keeper for harshsinghal.me
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a webpage which shows **real-time** data from this [Github repository](https://github.com/harsh778/harshsinghal.me-status) in order to display the live status of my [Personal Website](https://harshsinghal.me).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Personal Website
      href: https://harshsinghal.me
