owner: harsh778 
repo: harshsinghal.me-status 

sites:
  - name: Harsh Vardhan Singhal
    url: https://harshsinghal.me

status-website:

  baseUrl: /harshsinghal.me-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Keeper for harshsinghal.me
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Personal Website
      href: https://harshsinghal.me
